### model
model_name_or_path: ./sft/outputs/qwen15_code_full_sft
trust_remote_code: true

### method
stage: sft
do_predict: true
finetuning_type: full

### dataset
dataset_dir: ./sft/data
eval_dataset: mbpp_sanitized_test
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2

### output
output_dir: ./sft/outputs/qwen15_code_full_predict
overwrite_output_dir: true
report_to: none

### generation
per_device_eval_batch_size: 2
predict_with_generate: true
max_new_tokens: 768
do_sample: false
num_beams: 1
fp16: true
ddp_timeout: 180000000
